name: "Setup State Tool CLI"
description: "Sets up the ActiveState State Tool CLI in your GitHub Actions workflow."
inputs:
  version:
    description: "Version of the State Tool CLI to install"
    required: false
  channel:
    description: "Channel to download the State Tool CLI from"
    required: false
    default: "release"
  opt-in:
    description: "Flag to opt-in to unstable features"
    required: false
    default: "false"
  activestate-api-key:
    description: "API key used to authenticate to the ActiveState platform"
    required: true
branding:
  icon: 'download-cloud'
  color: 'red'
runs:
  using: "composite"
  steps:
  - name: "Install State Tool CLI (Linux & Darwin)"
    if: runner.os == 'Linux' || runner.os == 'macOS'
    shell: "bash"
    run: |
      installArgs=""
      if [ "${{ inputs.version }}" ]; then
        installArgs="-v ${{ inputs.version }} "
      fi
      CHANNEL="${{ inputs.channel }}"
      installArgs="${installArgs}-b $CHANNEL"
      sh <(curl -q https://platform.activestate.com/dl/cli/install.sh) $installArgs
      echo "$HOME/.local/ActiveState/StateTool/$CHANNEL/bin" >> $GITHUB_PATH
      echo "ACTIVESTATE_API_KEY=${{ inputs.activestate-api-key }}" >> $GITHUB_ENV
      "$HOME/.local/ActiveState/StateTool/$CHANNEL/bin/state" config set optin.unstable ${{ inputs.opt-in }}
  - name: "Install State Tool CLI (Windows)"
    if: runner.os == 'Windows'
    shell: "pwsh"
    run: |
      $installArgs = "-n "
      if ( "${{ inputs.version }}" )
      {
        $installArgs = "${installArgs}-v ${{ inputs.version }} "
      }
      $CHANNEL = "${{ inputs.channel }}"
      $installArgs = "${installArgs}-b $CHANNEL"
      (New-Object Net.WebClient).DownloadFile("https://platform.activestate.com/dl/cli/install.ps1", "install.ps1"); 
      Invoke-Expression -Command ".\install.ps1 -n $installArgs"
      echo "$env:LOCALAPPDATA\ActiveState\StateTool\$CHANNEL\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      echo "ACTIVESTATE_API_KEY=${{ inputs.activestate-api-key }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      $stateConfigCmd = "$env:LOCALAPPDATA\ActiveState\StateTool\$CHANNEL\bin\state config set optin.unstable ${{ inputs.opt-in }}"
      Invoke-Expression $stateConfigCmd
